title: Літопис Краю
description: Електронний архів броварської міськрайонної газети "Нове Життя"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://litopys.brovary.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
permalink: /:title/

# Collections
collections:
  pages:
    output: true
    permalink: /:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      coverImage: "/wp-content/uploads/2025/05/mpz3.png"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      coverImage: "/wp-content/uploads/2025/05/mpz3.png"
      permalink: /:title/
  - scope:
      path: "404.md"
    values:
      layout: "home"
      permalink: /404.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor